### ISSUE TITLE
CellMLImporterError due to element <min/>

### ISSUE THREAD

**Issue by ThomasMBury** [myokit/myokit#1099]
Hi Michael,

I'm trying to convert a CellML v1.0 file to a myokit .mmt file.

The CellML file has elements that use the min operator like this:
```
<apply>
    <min/>
    <ci>lambda_max</ci>
    <ci>lambda</ci>
</apply>
```

This raises the error
`myokit.formats.cellml._importer.CellMLImporterError: Error on line 3547. Unsupported element in apply: {http://www.w3.org/1998/Math/MathML}min.`

Is <min/> not supported in the conversion? If so, can you think of a workaround?

Thanks!

**Comment by MichaelClerx** [comment]
Hi @ThomasMBury ,
CellML 1.0 and 1.1 don't define the min and max operators (they are not part of the "CellML subset").

You can work around it by replacing it with a piecewise, e.g.
```
<piecewise>
    <piece>
        <ci>lambda_max</ci>
        <apply>
            <leq/>
            <ci>lambda_max</ci>
            <ci>lambda</ci>
        </apply>
    </piece>
    <otherwise>
        <ci>lambda</ci>
    </otherwise>
</piecewise>
```

(double-check that before using!)

**Comment by ThomasMBury** [comment]
Thanks for the quick response Michael - I'll play around with <piecewise>.

**Comment by ThomasMBury** [comment]
Oh great, thank you!
