### ISSUE TITLE
Revisit expression writers, reduce over-bracketing

### ISSUE THREAD

**Issue by MichaelClerx** [myokit/myokit#112]
In many cases, the bracket rules are the same as those for Myokit, so we can use the `Expression.bracket(Expression)` method to check if extra brackets are required.

To check

- [ ] python
  - [ ] ansic
    - [ ] cpp
  - [ ] cuda
  - [ ] easyml
  - [ ] matlab
  - [ ] numpy
  - [ ] opencl
  - [ ] stan
- [ ] latex
- [ ] mathml
  - [ ] cellml
- [ ] sympy

**Comment by MichaelClerx** [comment]
See also: https://github.com/MichaelClerx/myokit/issues/223

**Comment by MichaelClerx** [comment]
Some extra ones are needed to allow for differences in languages. For example, in matlab and myokit a^b^c means (a^b)^c, but in Python it means a^(b^c), and so brackets should be added to write (a^b)^c explicitly when exporting to Python

**Comment by mirams** [comment]
I didn't know different languages read things like that differently. Don't these IEEE people make rules for such things! People might expect to paste python code into myokit and have the same answer, any way to just insist on or add brackets to all generated code where things could be 'ambiguous' pasting around cross language?

**Comment by MichaelClerx** [comment]
The copy-pasting will always be a problem, I guess, but at least when you copy-paste cross-language you know that you are doing it, and so will hopefully do some sanity checks

For the output, I would expect it to just work, so yeah we can definitely err on the side of brackets. Compilers will deal with all that anyway.

It _would be nice_ for the formatting outputs (html, latex) to have nice code, but just a would-be-nice, so again over-bracketing probably not the problem

**Comment by MichaelClerx** [comment]
The argument made in the original issue, that bracketing rules are the same in most languages, isn't valid. There are lots of cases where extra brackets come in.
For example
-  `--x` should become `-(-x)` in languages with a `--` operator
- substitutions like `log(a, b) --> (log(a) / log(b))` require extra brackets, because the bracket-adding code expects a FUNCTION level operator, but a PRODUCT level operator has been used instead
- substitutions involving quotient and remainder can add extra brackets
