### ISSUE TITLE
Where to place Dockerfile for myokit?

### ISSUE THREAD

**Issue by teosbpl** [myokit/myokit#497]
Dear Michael,
my PhD student Sebastian Wildowicz has prepared a working Dockerfile for myokit.
How about putting it in source tree?
If you vote for: "yes" give us the path and we will prepare pull request.
Also: you can give rw rights to the repo to user swildowicz
Rgds 
TB

**Comment by MichaelClerx** [comment]
Hi Teodor,
Thanks!
What size is the file? If it's a single file I'm happy for it to go in the project root.

**Comment by MichaelClerx** [comment]
> Also: you can give rw rights to the repo to user swildowicz

I haven't set up this repository for multiple users yet (and there are some restrictions on private github accounts), so it's probably best to fork and make a pull request from there

**Comment by teosbpl** [comment]
Dear Michael,
the file is small but adding a few words to user documentation could help as well.
I’m adding Sebastian Wildowicz to this conversation, Please discuss further details with him directly
Cheers
Teodor
Wysłane z iPhone'a

Wiadomość napisana przez Michael Clerx <notifications@github.com> w dniu 11.03.2020, o godz. 15:38:

﻿

Hi Teodor,
Thanks!
What size is the file? If it's a single file I'm happy for it to go in the project root.

**Comment by MichaelClerx** [comment]
Thanks!

Hi Sebastian,
Thanks for your work!
Could you make a fork of this repo and then create a PR for the docker file?
We can discuss further things like documentation in that PR then

**Comment by teosbpl** [comment]
Dear Michael,
the size of the file is about 8kB. I included it in attachments.
I used pip3 for install Myokit on this docker image, but I suppose is
better to clone installer directly from your gitHub, could you confirm it ?
I can do some changes with this dockerfile to be sure that is stable and
workable for the long time.
Could you revied this file?
Thank you,
Kind Regards,
Sebastian

śr., 11 mar 2020 o 17:22 Buchner Teodor <teodor.buchner@pw.edu.pl>
napisał(a):

**Comment by MichaelClerx** [comment]
Thanks sebastian!

I'm afraid I can't see the attached file, github lets you do some things via email but mostly it's best to just use the web interface.

Installing with pip3 is the preferred option. (Installing from github is intended for developers)

Thanks again, I'm looking forward to trying out this docker file
