### ISSUE TITLE
conversion from g to nmol

### ISSUE THREAD

**Issue by martinjrobins** [myokit/myokit#887]
I want to use `conversion_factor(unit1, unit2, helpers=None)` to convert between [g] to [nmol]. I'm guessing that I can use `helpers` in some way by specifying the molecular weight of the compound, but the documentation for this arg is not clear. How can I do this?

**Comment by MichaelClerx** [comment]
You would have to provide a `Quantity` (or a string representation) to convert from g to nmol, so e.g. `"100 [g/nmol]"`.
The interface assumes a list of helpers, so it'd have to be e.g. `["100 [g/nmol]"]`, or `[myokit,Quantity(100, 'g/nmol')]`or something like that.

Does that help? I'm very happy to discuss ways to improve the docs.

(Also, the `Quantity` class is pretty obscure, and it's on the to-do list to move all its functionality into `Number`: https://github.com/myokit/myokit/issues/798 )

**Comment by martinjrobins** [comment]
Yes, that helps, a couple of questions:
1. Does the equation `[unit1] * c = 1 [unit2]` still hold for the returned conversion factor `c`? i.e. is the helper incorporated into `c`?
2. Is `c` independent of the units that I give for the helper. i.e. what if I provide `1e-6 [g/mol]`
3. Why can I provide a list of helpers, what is the advantage here?

**Comment by MichaelClerx** [comment]
>     1. Does the equation `[unit1] * c = 1 [unit2]` still hold for the returned conversion factor `c`? i.e. is the helper incorporated into `c`?

Yup! 

>     2. Is `c` independent of the units that I give for the helper. i.e. what if I provide `1e11 [g/mol]`, or even `1e-2 [nmol/g]`?
Did you look at the code or just guess this? :D 
Yes those are exactly the 2 additional cases it handles: the helper is scaled as necessary and possibly even inverted.

>     3. Why can I provide a list of helpers, what is the advantage here?

This just makes it easier to convert several variables with the same syntax. E.g. 

```
helpers=[case1, case2, case3]
for unit in list_including_case_1_2_and_3:
    convert(unit, helpers)
```

**Comment by MichaelClerx** [comment]
Do you think the updates in https://github.com/myokit/myokit/pull/888 are enough to clarify this for future users?

**Comment by martinjrobins** [comment]
Thanks @MichaelClerx, that is great :) I've added a review on #888 (all looks good) and can close this now

**Comment by MichaelClerx** [comment]
Thanks @martinjrobins !
I can't believe you found this feature 😆

**Comment by martinjrobins** [comment]
Thankyou for implementing such an excellent library :) The Unit's in myokit are very useful and we use them extensively in the pkpdapp so that users can upload their own models and datasets in their own units and still perform inference on them. We do all the unit conversion stuff in the backend, and store units in a db table by just storing the multiplier and exponents.
