### ISSUE TITLE
state variable with an initial condition dependent on another (constant) variable

### ISSUE THREAD

**Issue by martinjrobins** [myokit/myokit#898]
I'm trying to define a state variable in a myokit model, that has a default state that is an expression containing other constant variables. Is this possible? From the docs I suspect it is not, and the default state must be a concrete value?

**Comment by martinjrobins** [comment]
if it does have to be a value, would it be feasible to change this so it could be an expression?

**Comment by MichaelClerx** [comment]
At the moment it's not possible.

I'm not sure how hard it would be to implement this. Some things to think about:

- The model API would have to allow it
  - Any existing checks for cyclic dependencies should be triggered when an initial value is evaluated
  - Can one initial value depend on another? If so, need to extend cyclical checks
- Probably want to restrict constants to non-nested ones? E.g. would it be problematic to have x with initial value x.y ?
- Parser would need updating
- Exports would all need checking:
  - code exports would need to ensure state initialisation is after constant initialisation
  - language exports would need to check the target language supports it
- Sims would need checking (same a runnable code exports above)
- CVODES sim would need checking: does this create weird situations? Not sure! For one thing, if an initial value is no longer a literal, then maybe dy/dq would not allow non-literal initial values as q ?

None of those seem insurmountable, but plenty to think about, and creates lots of new situations that are not covered by the existing unit tests.

**Comment by MichaelClerx** [comment]
Would make this ticket easier: https://github.com/myokit/myokit/issues/500

**Comment by martinjrobins** [comment]
all sounds doable. If you don't mind I'll start having a go at this. I need to dive into how myokit does everything a bit more to understand what to do, so I'll start with that :)

**Comment by martinjrobins** [comment]
I think for simplicitly we would restrict initial value expressions to only consist of constants and constant variables

**Comment by MichaelClerx** [comment]
Cool! But expect days rather than hours

**Comment by MichaelClerx** [comment]
I think you should be able to create branches on this repo? If you don't want to work in a fork. I'm happy to look at draft PRs and such!

**Comment by martinjrobins** [comment]
Thanks, working on the repo directly would be preferred. I'll start work on this next week and will push a new branch then
