### ISSUE TITLE
2D cable simulation: change a constant of the model only for some cells

### ISSUE THREAD

**Issue by melaniabuonoc** [myokit/myokit#919]
Hey Michael,
Is it possible to change a constant of the model but only in a bunch of cells?
I am simulating a tissue cable with n cells, but  I would only want to change the value of the variable for some of them (for instance the central ones) and run the full simulation. The idea is to introduce some spatial heterogeneity.
Thank you!

**Comment by MichaelClerx** [comment]
Hi Melanie,

You can add in heterogeneity in cell tissues with: [`set_field`](https://myokit.readthedocs.io/en/stable/api_simulations/SimulationOpenCL.html#myokit.SimulationOpenCL.set_field)
(And remove it again with `remove_field`)

Heterogeneity in conductance parameters can be added with [`set_conductance_field`](https://myokit.readthedocs.io/en/stable/api_simulations/SimulationOpenCL.html#myokit.SimulationOpenCL.set_conductance_field) or go fully manual with [`set_connections`](https://myokit.readthedocs.io/en/stable/api_simulations/SimulationOpenCL.html#myokit.SimulationOpenCL.set_connections)

**Comment by melaniabuonoc** [comment]
Thank you Michael,
I am probably not fully getting it.

So let's say I have a cable of n=3 cells and I want to change 'SACs.Lambda' from 1 (value in the model definition) to 1.3, only in the second cell. 
I am using:

`   lam = np.zeros((1 , 3))
    lam = (1 , 1.3 , 1)
    s.set_field('SACs.Lambda' , lam)`

And I get a variation in all the cells.
How do I apply the change in SACs.Lambda only in the second cell?

**Comment by MichaelClerx** [comment]
The code above should actually do it (although note the second part `lam = (1, 1.3, 1)` replaces the numpy array you just created with a tuple)

You might not see much of a difference if there's only three cells though? Especially with strong coupling? To see an effect, maybe try:

1. A more extreme change, set something important like gKr = 0 in one cell
2. More cells: use 100 and give 30 of them a different lambda value. I'm assuming in the top example you have the default settings of pacing the first 5 cells, so all of them will be paced too? That can hide a lot (the pacing can be the dominant effect in the paced cells if it's strong)
3. No diffusion: In the above example both cells with lambda=1 are directly coupled to a cell with lambda=1.3, so the effect might be dampened?

**Comment by melaniabuonoc** [comment]
Using more cells did the job! Thank you for the explanation
