### ISSUE TITLE
initial condition for time

### ISSUE THREAD

**Issue by martinjrobins** [myokit/myokit#928]
So in a myokit model you can set initial conditions for the state variables. But how can you set the value for time where these initial conditions are defined? Is this possible or is t:=0 for the initial conditions?

**Comment by martinjrobins** [comment]
perhaps `model.time().set_rhs(value)`?

**Comment by MichaelClerx** [comment]
It's t:=0 by definition. I think it even says that in the docs somewhere. Reasoning being that it makes everything SO much simpler, without closing any doors (if you want t0=123 you just add 123 to the results)

**Comment by martinjrobins** [comment]
fair 'nuf :)

**Comment by MichaelClerx** [comment]
To-do:

- [ ] Add mention of this to mmt syntax doc
- [ ] Add mention of this to "Pacing protocols" doc

**Comment by MichaelClerx** [comment]
In other words, a model defines a relationship over a space, not a single trajectory :D

**Comment by MichaelClerx** [comment]
And of course mere weeks later a use case with negative times pops up :D

**Comment by MichaelClerx** [comment]
Will be adding an `initial_time` as part of #937
