### ISSUE TITLE
Add a method called e.g. `load2` that loads model and protocol, but ignores scripts

### ISSUE THREAD

**Issue by MichaelClerx** [myokit/myokit#931]
To avoid ugly `m, p, _ = myokit.load('...')` syntax

Or `load_mp('...')`?

**Comment by MichaelClerx** [comment]
Hey @martinjrobins @DavAug @Rebecca-Rumney @chonlei would you use a method like this? Any thoughts on the best name?

**Comment by martinjrobins** [comment]
not sure, I definitely would want to do something like this though.

`m, p, _ = myokit.load(' ')` seems ok though, it is very explicit about what your doing (i.e. dropping the script)

**Comment by MichaelClerx** [comment]
OK, closing this then!
