### ISSUE TITLE
import_component does not respect initial expressions

### ISSUE THREAD

**Issue by martinjrobins** [myokit/myokit#946]
when importing a component using `import_component`, any state variable initial expressions are converted to literal values

**Comment by MichaelClerx** [comment]
https://github.com/myokit/myokit/blob/main/myokit/tests/test_model.py#L1008

strange!

**Comment by martinjrobins** [comment]
huh, weird. Ok, I'll go back to my code and try and work out what is going on.....

**Comment by martinjrobins** [comment]
my fault, had an older version of myokit installed.....
