### ISSUE TITLE
unit conversion between mols <-> grams using molecular weight

### ISSUE THREAD

**Issue by martinjrobins** [myokit/myokit#996]
Say I have a function which returns the multiplication factor that I need to convert from one unit `from_unit` to another `to_unit`:

```python
 def _convert_unit(from_unit: myokit.Unit, to_unit: myokit.Unit, value: float):
   molecular_weight = '100 [g/mol]'
   conversion_factor = myokit.Unit.conversion_factor(
     variable.unit.get_myokit_unit(),
     myokit_variable_sbml.unit()
     helpers=[molecular_weight]
   ).value()
   return conversion_factor
```

now, lets assume that `from_unit` or `to_unit` could have any values for the `g` and `mol` exponents, but that I have the molecular weight, so I should be able to convert between these.

Is this how the `helpers` arg is meant to work, will this convert between, say, any of these units:

```
1/h*L/nmol
1/day*L/nmol
1/h*mL/ug
1/h*mL/ng
```

**Comment by MichaelClerx** [comment]
That's the idea, yeah!

**Comment by martinjrobins** [comment]
thanks!
